# -*- coding: utf-8 -*-
"""CIFAR100_Object_Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GcqeEYFhxpNecsPAxgfe3HMn_qLvufiH

# Object Recognition using CIFAR-100
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset_path = '/content/drive/MyDrive/Colab Notebooks/Applied_ML_Coursework/'

trnImage = np.load(dataset_path + 'trnImage.npy')
trnLabel_fine = np.load(dataset_path + 'trnLabel_fine.npy')
trnLabel_coarse = np.load(dataset_path + 'trnLabel_coarse.npy')

tstImage = np.load(dataset_path + 'tstImage.npy')
tstLabel_fine = np.load(dataset_path + 'tstLabel_fine.npy')
tstLabel_coarse = np.load(dataset_path + 'tstLabel_coarse.npy')

"""The CIFAR-100 training and testing datasets were loaded, including both fine and coarse category labels."""

print("Training images shape:", trnImage.shape)
print("Testing images shape:", tstImage.shape)

print("Training fine labels shape:", trnLabel_fine.shape)
print("Testing fine labels shape:", tstLabel_fine.shape)

trnImage = np.transpose(trnImage, (3, 0, 1, 2))
tstImage = np.transpose(tstImage, (3, 0, 1, 2))

print("New training shape:", trnImage.shape)
print("New testing shape:", tstImage.shape)

plt.imshow(trnImage[0])
plt.title("Sample Training Image")
plt.axis('off')
plt.show()

print("Fine label:", trnLabel_fine[0])
print("Coarse label:", trnLabel_coarse[0])

fine_labels = pd.read_csv(dataset_path + 'fine_labels.csv', header=None)
coarse_labels = pd.read_csv(dataset_path + 'coarse_labels.csv', header=None)

print(fine_labels.head())
print(coarse_labels.head())

fine_labels.iloc[0, 19]

fine_name = fine_labels.iloc[0, trnLabel_fine[0]]
coarse_name = coarse_labels.iloc[0, trnLabel_coarse[0]]

print("Fine category:", fine_name)
print("Coarse category:", coarse_name)

plt.figure(figsize=(4,4))
plt.imshow(trnImage[0])
plt.title(fine_labels.iloc[0, trnLabel_fine[0]])
plt.axis('off')
plt.show()

image_index = 25

plt.figure(figsize=(4,4))
plt.imshow(trnImage[image_index])
plt.title(fine_labels.iloc[0, trnLabel_fine[image_index]])
plt.axis('off')
plt.show()

from skimage.feature import hog

"""HOG was imported to extract image features that can be used with traditional machine learning classifiers."""

sample_features, hog_image = hog(
    trnImage[0],
    pixels_per_cell=(8, 8),
    cells_per_block=(2, 2),
    visualize=True,
    channel_axis=-1
)

print("HOG feature vector shape:", sample_features.shape)

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(trnImage[0])
plt.title("Original Image")
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(hog_image, cmap='gray')
plt.title("HOG Image")
plt.axis('off')

plt.show()

image_index = 25

sample_features, hog_image = hog(
    trnImage[image_index],
    pixels_per_cell=(8, 8),
    cells_per_block=(2, 2),
    visualize=True,
    channel_axis=-1
)

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(trnImage[image_index])
plt.title(fine_labels.iloc[0, trnLabel_fine[image_index]])
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(hog_image, cmap='gray')
plt.title("HOG Image")
plt.axis('off')

plt.show()

X_train_hog = []
X_test_hog = []

for image in trnImage:
    features = hog(
        image,
        pixels_per_cell=(8, 8),
        cells_per_block=(2, 2),
        channel_axis=-1
    )
    X_train_hog.append(features)

for image in tstImage:
    features = hog(
        image,
        pixels_per_cell=(8, 8),
        cells_per_block=(2, 2),
        channel_axis=-1
    )
    X_test_hog.append(features)

X_train_hog = np.array(X_train_hog)
X_test_hog = np.array(X_test_hog)

"""HOG features were extracted from all training and testing images to prepare the dataset for traditional machine learning models."""

print("Training HOG shape:", X_train_hog.shape)
print("Testing HOG shape:", X_test_hog.shape)

from sklearn.decomposition import PCA

"""PCA was imported to reduce the number of features while keeping the most important image information."""

pca = PCA(n_components=100)

X_train_pca = pca.fit_transform(X_train_hog)
X_test_pca = pca.transform(X_test_hog)

print("Original HOG shape:", X_train_hog.shape)
print("Reduced PCA shape:", X_train_pca.shape)

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

"""The SVM classifier and evaluation metric were imported for image classification and performance measurement."""

svm_model = SVC(kernel='rbf')

svm_model.fit(X_train_pca, trnLabel_fine)

"""The SVM model was trained using the PCA-reduced HOG features and the fine category labels."""

svm_predictions = svm_model.predict(X_test_pca)

"""The trained SVM model was used to predict the categories of the testing images."""

svm_accuracy = accuracy_score(tstLabel_fine, svm_predictions)

print("SVM Accuracy:", svm_accuracy)

svm_model_coarse = SVC(kernel='rbf')

svm_model_coarse.fit(X_train_pca, trnLabel_coarse)

svm_coarse_predictions = svm_model_coarse.predict(X_test_pca)

svm_coarse_accuracy = accuracy_score(tstLabel_coarse, svm_coarse_predictions)

print("SVM Coarse Accuracy:", svm_coarse_accuracy)

"""The SVM model was trained and evaluated using coarse labels, which group the images into 20 broader categories instead of 100 fine categories."""

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(tstLabel_coarse, svm_coarse_predictions)

plt.figure(figsize=(10,8))
sns.heatmap(cm, cmap='Blues')

plt.title("SVM Confusion Matrix - Coarse Labels")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.show()

cm = confusion_matrix(tstLabel_coarse, svm_coarse_predictions)

plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.title("SVM Confusion Matrix - Coarse Labels")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.show()

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

"""TensorFlow and Keras layers were imported to build the Convolutional Neural Network (CNN) model.

"""

trnImage_cnn = trnImage.astype('float32') / 255.0
tstImage_cnn = tstImage.astype('float32') / 255.0
#The image pixel values were normalized to improve CNN training performance.

cnn_model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(32,32,3)),
    MaxPooling2D((2,2)),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D((2,2)),

    Flatten(),

    Dense(128, activation='relu'),
    Dense(100, activation='softmax')
])
#A CNN architecture was created for image classification using convolution, pooling, and dense layers.

cnn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = cnn_model.fit(
    trnImage_cnn,
    trnLabel_fine,
    epochs=10,
    batch_size=64,
    validation_data=(tstImage_cnn, tstLabel_fine)
)

print(trnLabel_fine.shape)
print(trnLabel_fine.dtype)

print(np.unique(trnLabel_fine)[:10])

print("Min pixel value:", trnImage.min())
print("Max pixel value:", trnImage.max())
print("Data type:", trnImage.dtype)

# The images were already normalized between 0 and 1.
# Dividing by 255 again caused the CNN training issue.
# The normalization step was corrected below.

trnImage_cnn = trnImage.astype('float32')
tstImage_cnn = tstImage.astype('float32')

"""During the initial CNN training, the model achieved very low accuracy because the image data had already been normalized between 0 and 1. Dividing the images by 255 again made the pixel values extremely small, preventing the CNN from learning properly. After identifying the issue, the normalization step was corrected and the CNN model was rebuilt and retrained using the corrected image data."""

cnn_loss, cnn_accuracy = cnn_model.evaluate(tstImage_cnn, tstLabel_fine)

print("CNN Accuracy:", cnn_accuracy)

cnn_predictions = cnn_model.predict(tstImage_cnn)

cnn_predictions = np.argmax(cnn_predictions, axis=1)

cnn_cm = confusion_matrix(tstLabel_fine, cnn_predictions)

plt.figure(figsize=(12,10))
sns.heatmap(cnn_cm, cmap='Blues')

plt.title("CNN Confusion Matrix - Fine Labels")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.show()

plt.figure(figsize=(8,5))

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.title('CNN Training Performance')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.show()

comparison_models = ['SVM (Fine)', 'SVM (Coarse)', 'CNN (Fine)']
comparison_accuracy = [0.282, 0.3958, 0.3669]

plt.figure(figsize=(7,5))
plt.bar(comparison_models, comparison_accuracy)

plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison")

plt.show()

"""The performance of the implemented models was compared using their classification accuracies."""

from sklearn.metrics import classification_report

print(classification_report(tstLabel_fine, cnn_predictions))

sample_index = 50

plt.figure(figsize=(4,4))
plt.imshow(tstImage[sample_index])

predicted_label = fine_labels.iloc[0, cnn_predictions[sample_index]]
true_label = fine_labels.iloc[0, tstLabel_fine[sample_index]]

plt.title(f"Predicted: {predicted_label}\nActual: {true_label}")
plt.axis('off')

plt.show()

sample_index = 7

plt.figure(figsize=(4,4))
plt.imshow(tstImage[sample_index])

predicted_label = fine_labels.iloc[0, cnn_predictions[sample_index]]
true_label = fine_labels.iloc[0, tstLabel_fine[sample_index]]

plt.title(f"Predicted: {predicted_label}\nActual: {true_label}")
plt.axis('off')

plt.show()

correct_indices = np.where(cnn_predictions == tstLabel_fine)[0]

print("Number of correct predictions:", len(correct_indices))
print("First 10 correct indices:", correct_indices[:10])

sample_index = correct_indices[0]

plt.figure(figsize=(4,4))
plt.imshow(tstImage[sample_index])

predicted_label = fine_labels.iloc[0, cnn_predictions[sample_index]]
true_label = fine_labels.iloc[0, tstLabel_fine[sample_index]]

plt.title(f"Predicted: {predicted_label}\nActual: {true_label}")
plt.axis('off')
plt.show()



incorrect_indices = np.where(cnn_predictions != tstLabel_fine)[0]

print("Number of incorrect predictions:", len(incorrect_indices))

sample_index = incorrect_indices[0]

plt.figure(figsize=(4,4))
plt.imshow(tstImage[sample_index])

predicted_label = fine_labels.iloc[0, cnn_predictions[sample_index]]
true_label = fine_labels.iloc[0, tstLabel_fine[sample_index]]

plt.title(f"Predicted: {predicted_label}\nActual: {true_label}")
plt.axis('off')
plt.show()

plt.figure(figsize=(8,5))

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.title('CNN Loss Performance')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.show()

print("SVM Fine Accuracy:", svm_accuracy)
print("SVM Coarse Accuracy:", svm_coarse_accuracy)
print("CNN Fine Accuracy:", cnn_accuracy)
#The final accuracy results of the implemented models were summarized for comparison.

cnn_model.summary()

plt.figure(figsize=(12,5))

for i in range(5):
    plt.subplot(1,5,i+1)
    plt.imshow(tstImage[i])

    predicted = fine_labels.iloc[0, cnn_predictions[i]]
    actual = fine_labels.iloc[0, tstLabel_fine[i]]

    plt.title(f"P:{predicted}\nA:{actual}", fontsize=8)
    plt.axis('off')

plt.tight_layout()
plt.show()

best_accuracy = max(svm_accuracy, svm_coarse_accuracy, cnn_accuracy)

print("Best Model Accuracy:", best_accuracy)

print("Coursework Benchmark (Fine): 24.49%")
print("Our SVM Fine Accuracy:", round(svm_accuracy * 100, 2), "%")
print("Our CNN Fine Accuracy:", round(cnn_accuracy * 100, 2), "%")

print("Coursework Benchmark (Coarse): 39.43%")
print("Our SVM Coarse Accuracy:", round(svm_coarse_accuracy * 100, 2), "%")

"""The implementation, training, evaluation, and comparison of the machine learning models were completed successfully.

## Project Summary

In this project, the CIFAR-100 dataset was loaded and prepared for image classification using both traditional machine learning and deep learning approaches. The dataset consisted of training and testing images with both fine and coarse category labels. After loading the dataset, the image dimensions were checked and rearranged into a format compatible with machine learning models.

Several sample images were visualized to better understand the dataset, and the label files were loaded to convert numerical labels into readable category names.

For the traditional machine learning approach, HOG (Histogram of Oriented Gradients) features were extracted from the images to capture important edge and shape information. PCA (Principal Component Analysis) was then applied to reduce the feature dimensions while preserving the most important information. These processed features were used to train SVM (Support Vector Machine) classifiers using both fine and coarse labels.

The SVM model achieved an accuracy of 28.2% on the fine categories and 39.58% on the coarse categories, slightly exceeding the benchmark provided in the coursework.

A Convolutional Neural Network (CNN) was also implemented using TensorFlow and Keras. During the first training attempt, the CNN achieved very low accuracy because the images had already been normalized between 0 and 1, and dividing them again by 255 caused the pixel values to become too small. After identifying the issue, the normalization step was corrected and the CNN model was rebuilt and retrained.

The CNN architecture included convolutional layers, max-pooling layers, a flatten layer, and dense layers for classification. After training for 10 epochs, the CNN achieved a fine-category classification accuracy of approximately 36.69%, outperforming the SVM fine-category model.

Finally, different evaluation techniques were used to analyze the models, including confusion matrices, classification reports, training and validation graphs, and prediction visualizations. Overall, the CNN achieved the best performance for fine-grained image classification, while the SVM coarse classifier slightly exceeded the coursework benchmark.
"""